import { Geist } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/context/CartContext'
import BottomNav from '@/components/BottomNav'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<BottomNav />
			<body className={`${geistSans.variable} antialiased`}>
				<CartProvider>{children}</CartProvider>
			</body>
		</html>
	)
}
